### PR TITLE
336 [SixTest] testVariance realise

### PR DESCRIPTION
**Pull request by Anastasiia3795**

### CODE REVIEW

**Review by andriyav — COMMENTED** [review]
my implementation doesn't pass the test :) because you didn't take into account delta 1e-2. It was mentioned in the task in codewars.com. 
I'd add delta in 
assertEquals(actual, expected, 1e-2, "Wrong variance function count");
please check.

**Review by DappY-127 — CHANGES_REQUESTED** [review]
В принципі погоджусь з Андрієм, і його варіант рішення теж валідний.

**Comment by Anastasiia3795** [comment]
I've just added, tests were passed, thanks

**Review by DappY-127 — APPROVED** [review]

**Review by andriyav — APPROVED** [review]
Thanks :)

**Pull request merged**
